#%RAML 0.8
  - songSchema: |
      {
      "$schema": "http://json-schema.org/schema",
      "type": "object", "description" : "The canonical song representation",
      "properties": {
         "title": {"type": "string"},
         "genre": {"type": "string"}
         "artist": {"type": "string"}
       },
       "required": ["title", "genre"]
      }
